---
- name: WEB | Install PHP and nginx
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - php
    - php-mysql
    - nginx

- name: WEB | Creates web directory
  file: path=/web state=directory

- stat: path="{{ wordpress_web_root }}"
  register: web_wordpress_dir

- name: WEB | Download worpdress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /web
    validate_certs: no
    remote_src: True
  when: web_wordpress_dir.stat.exists == False

- name: WEB | Copy wordpress config
  template:
    src: wp-config-sample.php
    dest: "{{ wordpress_web_root }}/wp-config.php"

- name: WEB | Configure nginx vhost
  template:
    src: wordpress.conf
    dest: /etc/nginx/sites-available/wordpress
  notify:
    - restart nginx

- name: WEB | Create symlink to vhost
  file: src=/etc/nginx/sites-available/wordpress dest=/etc/nginx/sites-enabled/wordpress state=link
  notify:
    - restart nginx
